### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dbourdette** [asciidoctor/atom-asciidoc-preview#104]
[Enter steps to reproduce below:]

1. create new file 
2. type some content (do not save)
3. open preview (cmd + shift + a)
4. right click + Save As HTML... 

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/dbourdette/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:242

TypeError: undefined is not a function
  at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.saveAs (/Users/dbourdette/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:242:37)
  at space-pen-div.atom.commands.add.core:save-as (/Users/dbourdette/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:94:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)

```

### Commands

```
     -0:08.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:07.5.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0

# Dev
No dev packages
```

**Comment by anthonny** [comment]
Thank you :+1:
