### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #eclipse-4-rcp/JPA-persistence.adoc

### ISSUE THREAD

**Issue by psuzzi** [asciidoctor/atom-asciidoc-preview#115]
[Enter steps to reproduce below:]

I'm writing a tutorial on eclipse and I found a problem referencing external files. 

1. create a project structure is like this: 

tutorials
   eclipse-4-rcp
      JPA-persistence.adoc
   eclipse-4-rcp.adoc
 
2. refer to JPA-persistence.adoc, from inside the other document: eclipse-4-rcp.adoc, located one level up, as follows:

* `JPA persistence: <<eclipse-4-rcp/JPA-persistence.adoc>>`

The step 2 will throw the error

**Atom Version**: 1.3.1
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: #eclipse-4-rcp/JPA-persistence.adoc

```
At C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:1458

Error: Syntax error, unrecognized expression: #eclipse-4-rcp/JPA-persistence.adoc
    at Function.Sizzle.error (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:1458:8)
    at Sizzle.tokenize (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:2075:11)
    at Sizzle.select (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:2479:20)
    at Function.Sizzle [as find] (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:855:9)
    at [object Object].jQuery.fn.extend.find (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:2695:11)
    at [object Object].jQuery.fn.init (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:2803:38)
    at jQuery (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:76:10)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.enableAnchorScroll (file:///C:/Users/p.suzzi/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:175:21)
    at file:///C:/Users/p.suzzi/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:147:8
    at Task.callback (file:///C:/Users/p.suzzi/.atom/packages/asciidoc-preview/lib/renderer.coffee:32:5)
    at C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\src\task.js:65:72
    at C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\src\task.js:126:25
    at Emitter.module.exports.Emitter.emit (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at ChildProcess.<anonymous> (C:\Users\p.suzzi\AppData\Local\atom\app-1.3.1\resources\app.asar\src\task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -6:55.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:54.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:42.7.0 tree-view:copy-full-path (span.name.icon.icon-file-directory)
  6x -1:51.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:48.9.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  7x -1:44.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33 core:save (atom-text-editor.editor.is-focused)
     -0:30.9.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
     -0:22 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.8.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
language-asciidoc, v0.12.0

# Dev
No dev packages
```

**Comment by Mogztter** [comment]
Related issues: #117 #115 #123 #125

**Comment by Mogztter** [comment]
Resolved in https://github.com/asciidoctor/atom-asciidoc-preview/pull/133
