### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #../data_structure/data.adoc

### ISSUE THREAD

**Issue by ZuYuanZhou** [asciidoctor/atom-asciidoc-preview#117]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: #../data_structure/data.adoc

```
At /Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:1458

Error: Syntax error, unrecognized expression: #../data_structure/data.adoc
    at Function.Sizzle.error (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:1458:8)
    at Sizzle.tokenize (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2075:11)
    at Sizzle.select (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2479:20)
    at Function.Sizzle [as find] (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:855:9)
    at [object Object].jQuery.fn.extend.find (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2695:11)
    at [object Object].jQuery.fn.init (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2803:38)
    at jQuery (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:76:10)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.enableAnchorScroll (/Users/Dio/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:175:21)
    at /Users/Dio/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:147:8
    at Task.callback (/Users/Dio/.atom/packages/asciidoc-preview/lib/renderer.coffee:32:5)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:65:72
    at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -2:01.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:47.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:43.3.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
     -1:28.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:15.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:08.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:05.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:04.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:59.5.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
  2x -0:58 core:move-down (atom-text-editor.editor.is-focused)
     -0:56.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:19.7.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
language-asciidoc, v0.12.0

# Dev
No dev packages
```

**Comment by Mogztter** [comment]
Related issues: #117 #115 #123 #125
