### ISSUE TITLE
Pane crashed after trying to split preview pane

### ISSUE THREAD

**Issue by zorceta** [asciidoctor/atom-asciidoc-preview#118]
Opened a file on the upper left pane, a temp pane on the lower left with language set to AsciiDoc, and a AsciiDoc preview pane on the right. Crash was after trying to split the preview pane to upper and lower panes.

**Atom Version**: 1.3.2
**System**: Windows 10 build 10240 64bit
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setFlexScale' of undefined

```
At C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-axis.js:222

TypeError: Cannot read property 'setFlexScale' of undefined
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-axis.js:222:16)
    at PaneAxis.module.exports.PaneAxis.removeChild (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-axis.js:188:21)
    at C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-axis.js:231:24
    at Emitter.module.exports.Emitter.emit (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.destroyed (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:648:20)
    at Pane.module.exports.Model.destroy (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\model.js:31:58)
    at Pane.module.exports.Pane.destroy (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:639:39)
    at Pane.module.exports.Pane.removeItem (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:411:21)
    at Pane.module.exports.Pane.destroyItem (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:453:16)
    at file:///C:/Users/Zorceta/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:71:44
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.resolveEditor (file:///C:/Users/Zorceta/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:74:7)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.attached (file:///C:/Users/Zorceta/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:28:8)
    at space-pen-div.View.element.attached (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:164:63)
    at space-pen-div.CustomElementPrototype.attachedCallback (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:51:55)
    at atom-pane-axis.PaneAxisElement.childAdded (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-axis-element.js:62:12)
    at atom-pane-axis.PaneAxisElement.childReplaced (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-axis-element.js:96:12)
    at Emitter.module.exports.Emitter.emit (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at PaneAxis.module.exports.PaneAxis.replaceChild (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-axis.js:200:27)
    at Pane.module.exports.Pane.split (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:692:21)
    at Pane.module.exports.Pane.splitDown (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:680:19)
    at atom-pane.commandRegistry.add.pane:split-down (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\register-default-commands.js:204:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Zorceta\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:14.4.0 pane:split-down (div.asciidoc-preview.native-key-bindings)
```

### Config

```json
{
  "core": {},
  "asciidoc-preview": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
hex, v0.6.2
language-asciidoc, v0.12.0

# Dev
No dev packages
```

**Comment by Mogztter** [comment]
Hello @zorceta could you explain how you resolved this issue ?

**Comment by zorceta** [comment]
@Mogztter I've not since used Atom.

**Comment by Mogztter** [comment]
Ok let me know if you hit this issue again, thanks :wink:
