### ISSUE TITLE
Save As HTML... : Uncaught TypeError: atom.project.getPath is not a function

### ISSUE THREAD

**Issue by soulpapa** [asciidoctor/atom-asciidoc-preview#119]
I right-click on preview page to save as html.

OS: OS X El-Capitan
Atom version: 1.4.1
# Stacktrace:

/Users/yoon/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:242
Hide Stack Trace
TypeError: atom.project.getPath is not a function
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.saveAs (/Users/yoon-yeojin/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:242:37)
    at space-pen-div.atom.commands.add.core:save-as (/Users/yoon-yeojin/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:94:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Users/yoon-yeojin/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

**Comment by IRus** [comment]
Same issue, ubuntu 15.10

**Comment by ldez** [comment]
Can you retry with the 1.0.0 ?
