### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #wsd-e.i.r.p.

### ISSUE THREAD

**Issue by akindo** [asciidoctor/atom-asciidoc-preview#123]
1. Opened an AsciiDoc file created with pandoc from a 400+ page Word file.
2. Enabled Atom AsciiDoc Preview plugin from the menu.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: #wsd-e.i.r.p.

```
At /opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:1458

Error: Syntax error, unrecognized expression: #wsd-e.i.r.p.
    at Function.Sizzle.error (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:1458:8)
    at Sizzle.tokenize (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:2075:11)
    at Sizzle.select (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:2479:20)
    at Function.Sizzle [as find] (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:855:9)
    at [object Object].jQuery.fn.extend.find (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:2695:11)
    at [object Object].jQuery.fn.init (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:2803:38)
    at jQuery (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:76:10)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.enableAnchorScroll (/Users/jannik/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:175:21)
    at /Users/jannik/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:147:8
    at Task.callback (/Users/jannik/.atom/packages/asciidoc-preview/lib/renderer.coffee:32:5)
    at /opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/src/task.js:65:72
    at /opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ChildProcess.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.0/Atom.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
  2x -0:24.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:03.9.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
jshint, v1.8.3

# Dev
No dev packages
```

**Comment by Mogztter** [comment]
Related issues: #117 #115 #123 #125

**Comment by Mogztter** [comment]
Resolved in https://github.com/asciidoctor/atom-asciidoc-preview/pull/133

**Comment by akindo** [comment]
Thanks, good work!
