### ISSUE TITLE
Uncaught TypeError: atom.workspace.open(...).done is not a function

### ISSUE THREAD

**Issue by ezmiller** [asciidoctor/atom-asciidoc-preview#124]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /Users/ethan/.atom/packages/asciidoc-preview/lib/asciidoc-preview.coffee:115

TypeError: atom.workspace.open(...).done is not a function
    at Object.module.exports.toggle (/Users/ethan/.atom/packages/asciidoc-preview/lib/asciidoc-preview.coffee:115:68)
    at atom-workspace.atom.commands.add.asciidoc-preview:toggle (/Users/ethan/.atom/packages/asciidoc-preview/lib/asciidoc-preview.coffee:46:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:30.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:30 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:26.1.0 editor:newline (atom-text-editor.editor.is-focused)
 16x -1:20.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.9.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:42.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:37.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:37 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  6x -0:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -0:14.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:05.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.8.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "asciidoc-preview": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
atom-beautify, v0.28.21
atom-handlebars, v1.3.0
autoclose-html, v0.20.0
language-asciidoc, v0.12.0
language-javascript-jsx, v0.3.7
lisp-paredit, v0.5.1
recent-projects, v0.9.5

# Dev
No dev packages
```

**Comment by winteryoung** [comment]
i believe this package conflicts with recent-projects

**Comment by ldez** [comment]
Can you retry with the 1.0.0 ?
