### ISSUE TITLE
Failed to activate the asciidoc-preview package

### ISSUE THREAD

**Issue by testn** [asciidoctor/atom-asciidoc-preview#190]
I was just trying to upgrade it

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v2.5.1

### Stack Trace

Failed to activate the asciidoc-preview package

```
At Cannot find module 'object-assign'

Error: Cannot find module 'object-assign'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nluengna/.atom/packages/asciidoc-preview/node_modules/opn/index.js:4:20)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nluengna/.atom/packages/asciidoc-preview/lib/pdf-converter.coffee:2:7)
    at Object.<anonymous> (/Users/nluengna/.atom/packages/asciidoc-preview/lib/pdf-converter.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nluengna/.atom/packages/asciidoc-preview/lib/main.coffee:5:16)
    at Object.<anonymous> (/Users/nluengna/.atom/packages/asciidoc-preview/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:398:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v2.5.1
atom-innerspace, v0.1.5
autocomplete-go, v1.1.0
builder-go, v1.0.0
color-picker, v2.1.1
environment, v1.2.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
hex, v0.6.2
language-asciidoc, v1.5.1
linter, v1.11.14
markdown-preview-plus, v2.4.0
merge-conflicts, v1.4.4
minimap, v4.24.6
navigator-godef, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by ldez** [comment]
Hello @testn,

Can you try this:
1. close Atom
2. in a shell `apm uninstall asciidoc-preview`
4. in a shell  `apm rebuild-module-cache`
5. in a shell  `apm install asciidoc-preview`
6. open Atom

**Comment by ldez** [comment]
@testn any news?

**Comment by testn** [comment]
It seems to work fine after doing that. Thanks!
