### ISSUE TITLE
 "save as html"  error

### ISSUE THREAD

**Issue by asktalk** [asciidoctor/atom-asciidoc-preview#203]
## Description
 when i run "save as html",:

Uncaught TypeError: Path must be a string. Received undefined
path.js:7
Hide Stack Trace
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.saveAs (file:///C:/Users/keep/.atom/packages/atom-asciidoc-preview/lib/asciidoc-preview-view.coffee:229:27)
    at space-pen-div.disposables.add.atom.commands.add.core:save-as (file:///C:/Users/keep/.atom/packages/atom-asciidoc-preview/lib/asciidoc-preview-view.coffee:91:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\keep\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\keep\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\keep\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\keep\AppData\Local\atom\app-1.12.5\resources\app.asar\src\atom-environment.js:1142:28)
    at EventEmitter.outerCallback (C:\Users\keep\AppData\Local\atom\app-1.12.5\resources\app.asar\src\application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

- Atom version:
- OS:
- `asciidoc-preview` version:2.6.0
- `language-asciidoc` version:1.6.2

## Screenshots

Your screenshot.

## Syntax example

```adoc
Your syntax example.
```

**Comment by ldez** [comment]
Can you give Atom Version, OS and step to reproduce ? Thanks.

**Comment by ldez** [comment]
Can you provide more information ? Otherwise I must closed this issue.
