### ISSUE TITLE
include from 2nd level asc file via tags is broken in v2.7.0

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/atom-asciidoc-preview#205]
## Description

Indirect code inclusion from 2nd level asc file stopped working in v2.7.0.  This worked in v2.6.0 . For some reason it now looks in the atom install directory for the python file.

- Atom version: 1.12.6
- OS: Windows 10
- `asciidoc-preview` version: 2.7.0
- `language-asciidoc` version: 1.6.2

## Syntax example
```
├── parent.asc
├── 2nd.asc
└── subdir\foo.py
```
## parent.asc
```adoc
include::2nd.asc[tags=test]
```
## 2nd.asc

```adoc
tag::test[]
[source,python]
-----
include::subdir/foo.py[tags=bar]
-----
end::test[]
```

## Error message

Asciidoctor.js error
```
Rendering error
Please verify your document syntax.

Details: Error: ENOENT: no such file or directory, open 'C:\Users\elefant\AppData\Local\atom\app-1.12.6\subdir\foo.py'

[code: ENOENT, errno: -4058, syscall: open]

Error: ENOENT: no such file or directory, open 'C:\Users\elefant\AppData\Local\atom\app-1.12.6\subdir\foo.py' 
at Error (native) 
at Object.fs.openSync (fs.js:640:18) 
at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20) 
at $File.ːinitialize (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:20294:40) 
at singleton_class_alloc.TMP_4 [as $new] (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\opal-runtime\src\opal.js:3139:23) 
at $PreprocessorReader.ːopen (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:20254:45) 
at $PreprocessorReader.ːpreprocess_include (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:31659:141) 
at $PreprocessorReader.ːprocess_line (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:31380:36) 
at $PreprocessorReader.ːpeek_line (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:30986:41) 
at $PreprocessorReader.ːpeek_line (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:31411:129) 
at $PreprocessorReader.TMP_6 [as $has_more_lines?] (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:30961:98) 
at $PreprocessorReader.ːread_line (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:31030:189) 
at $PreprocessorReader.ːread_lines_until (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:31193:102) 
at singleton_class_alloc.ːbuild_block (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:29202:26) 
at singleton_class_alloc.ːnext_block (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:29009:24) 
at singleton_class_alloc.ːnext_section (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:28642:40) 
at singleton_class_alloc.ːnext_section (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:28633:23) 
at singleton_class_alloc.ːparse (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:28479:21) 
at $Document.ːparse (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:27419:32) 
at module_constructor.ːload (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:33226:65) 
at module_constructor.ːconvert (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:33306:20) 
at module_constructor.Opal.Asciidoctor.$$class.$$proto.convert (C:\Users\elefant\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\asciidoctor.js:33455:21) 
at Object.module.exports (file:///C:/Users/elefant/.atom/packages/asciidoc-preview/lib/worker.coffee:34:24) 
at process. (C:\Users\elefant\AppData\Local\atom\app-1.12.6\resources\app.asar\src\task-bootstrap.js:84:10) at emitTwo (events.js:106:13) 
at process.emit (events.js:191:7) at process.nextTick (internal/child_process.js:744:12) at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Mogztter** [comment]
I think this is related to the fact that `Dir.pwd` now resolved to the Atom install.
Did you set the `base_dir` ?

**Comment by handcraftsman** [comment]
I'm using the default: {docdir}

When I roll back to v2.6.0 it works again.  Is this an expected change in behavior in v2.7.0?

**Comment by Mogztter** [comment]
I couldn't reproduce this issue on Linux, I will try on Windows

**Comment by ldez** [comment]
I reproduce on Linux

**Comment by ldez** [comment]
And it's not an expected change, it's a bug.

**Comment by Mogztter** [comment]
I found the root cause, this is an issue with Opal.

Ruby MRI:
```ruby
puts File.dirna­me('c:\dev­\playgroun­d\test.ado­c') # "c:\\dev\\playground"
```

Opal:
```javascript
console.log($scope.get('File').$dirname('c:\dev­\playgroun­d\test.ado­c')) // "."
```

In Ruby.c the method `isdirsep` is checking both Unix separator `/` and DOS separator `\`: https://github.com/ruby/ruby/blob/trunk/file.c#L2912

In Opal the method `isDirSep` is only checking for Unix separator: https://github.com/opal/opal/blob/master/opal/corelib/file.rb#L82

As a result "c:\dev­\playgroun­d\test.ado­c" is considered as a filename and not a path. 😢

**Comment by ldez** [comment]
@Mogztter I going to downgrade Asciidoctor.js to the previous version.

**Comment by ldez** [comment]
@handcraftsman the version 2.7.1 fixed "temporary" the bug.

**Comment by mojavelinux** [comment]
This is one of the main reasons that Asciidoctor core provides a [path resolver](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/path_resolver.rb). In particular, this utility has a method that forces all paths to forward slash. Windows can work with slashes in either direction, but to make paths work with the rest of the world, internally, the slashes should be facing forward.

Technically, though, Ruby (and thus Opal) is supposed to be able to do this itself.

**Comment by mojavelinux** [comment]
I call the utility [posixfy]( https://github.com/asciidoctor/asciidoctor/blob/1aaa1b89500e7c9c87c5cbe37a19a686695f885e/lib/asciidoctor/path_resolver.rb#L179-L187).

**Comment by Mogztter** [comment]
@mojavelinux Yes but in this case we are not using `posixfy` method because we are using a [special case for Opal](https://github.com/asciidoctor/asciidoctor/blob/2796abffbf7fbd32d46cd9df0bebff6ea0da7841/lib/asciidoctor/reader.rb#L838-L847). Though I wonder if this is still necessary with all the improvements made in Opal... :thinking: 

`posixfy` method is used in `system_path` and `web_path` method but in this case we are just using `:File.join @dir, target`.

On a side note, improvements on `File.join` will soon be available on Opal. I think this will cover most of the cases: https://github.com/opal/opal/pull/1585
