### ISSUE TITLE
no Preview, only "Loading AsciiDoc..."

### ISSUE THREAD

**Issue by arcusbude** [asciidoctor/atom-asciidoc-preview#304]
## Description

When enabling Preview for a simple adoc i get only the "Loading AsciiDoc..." Sign. In Browser console i see a stacktrace:

```
events.js:106 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(anonymous) @ <embedded>:76210
(anonymous) @ <embedded>:76284
module.exports.Emitter.simpleDispatch @ <embedded>:66749
module.exports.Emitter.emit @ <embedded>:66865
(anonymous) @ <embedded>:76236
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

```

- Atom version: 1.27.1 x64
- OS: Debian 9
- `asciidoc-preview` version: 2.13.1
- `language-asciidoc` version: 1.11.0

## Syntax example

```adoc
## sdfsdf
```

**Comment by mmacata** [comment]
I had the same problem with Atom 1.26.1. After an update of atom it is now working (to 1.54.0). `asciidoc-preview` is and was version 2.13.1.
